### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by snow922841** [rsalmei/alive-progress#29]
cannot import name 'alive_bar' from partially initialized module 'alive_progress' (most likely due to a circular import)

I use pycharm and python3.8

**Comment by rsalmei** [comment]
Hello @snow922841,

Please give me more details, it does work in PyCharm and Python 3.8, see:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/6652853/78799977-43a00200-7991-11ea-9bc0-8803698c245e.png">

Describe the steps you took exactly, and how you installed `alive_progress`.

**Comment by snow922841** [comment]
I'm sorry, it's not you. I used your project as the name of the folder and
caused the error

Rogério Sampaio de Almeida <notifications@github.com>于2020年4月8日 周三23:06写道：

**Comment by rsalmei** [comment]
I see, no problem. 👍
